<script lang="ts">
	import * as icons from '@lucide/svelte';

	let {
		name,
		size = 24,
		class: className = '',
		strokeWidth = 1.8
	}: {
		name: string;
		size?: number;
		class?: string;
		strokeWidth?: number;
	} = $props();

	const iconMap: Record<string, typeof icons.Home> = {
		home: icons.Home,
		list: icons.List,
		plus: icons.Plus,
		'bar-chart': icons.BarChart3,
		settings: icons.Settings,
		'chevron-left': icons.ChevronLeft,
		'chevron-right': icons.ChevronRight,
		'arrow-right': icons.ArrowRight,
		calendar: icons.Calendar,
		trash: icons.Trash2,
		edit: icons.Pencil,
		x: icons.X,
		utensils: icons.Utensils,
		car: icons.Car,
		tv: icons.Tv,
		gamepad: icons.Gamepad,
		'heart-pulse': icons.HeartPulse,
		house: icons.House,
		wallet: icons.Wallet,
		target: icons.Target,
		'piggy-bank': icons.PiggyBank,
		bell: icons.Bell,
		'triangle-alert': icons.TriangleAlert,
		'credit-card': icons.CreditCard,
		landmark: icons.Landmark,
		banknote: icons.Banknote,
		sparkles: icons.Sparkles,
		check: icons.Check,
		'chevron-down': icons.ChevronDown,
		globe: icons.Globe,
		'shopping-bag': icons.ShoppingBag,
		coffee: icons.Coffee,
		gift: icons.Gift,
		book: icons.Book,
		plane: icons.Plane,
		bus: icons.Bus,
		smartphone: icons.Smartphone,
		music: icons.Music,
		dumbbell: icons.Dumbbell,
		baby: icons.Baby,
		dog: icons.Dog,
		scissors: icons.Scissors,
		briefcase: icons.Briefcase,
		'graduation-cap': icons.GraduationCap,
		wrench: icons.Wrench,
		shirt: icons.Shirt,
		fuel: icons.Fuel,
		pill: icons.Pill,
		'arrow-left-right': icons.ArrowLeftRight,
		'play-circle': icons.PlayCircle,
		clapperboard: icons.Clapperboard,
		github: icons.Github,
		figma: icons.Figma,
		bot: icons.Bot,
		shield: icons.Shield,
		'hard-drive': icons.HardDrive,
		newspaper: icons.Newspaper,
		'gamepad-2': icons.Gamepad2,
		palette: icons.Palette,
		'file-spreadsheet': icons.FileSpreadsheet,
		'book-open': icons.BookOpen,
		phone: icons.Phone,
		wifi: icons.Wifi,
		cloud: icons.Cloud,
		package: icons.Package,
		film: icons.Film,
		youtube: icons.Youtube,
		slack: icons.Slack,
		twitch: icons.Twitch,
		search: icons.Search,
		'search-x': icons.SearchX,
		'sliders-horizontal': icons.SlidersHorizontal,
		star: icons.Star,
		zap: icons.Zap,
		droplets: icons.Droplets,
		flame: icons.Flame,
		'washing-machine': icons.WashingMachine,
		monitor: icons.Monitor,
		headphones: icons.Headphones,
		camera: icons.Camera,
		printer: icons.Printer,
		key: icons.Key,
		lock: icons.Lock,
		mail: icons.Mail,
		'message-circle': icons.MessageCircle,
		'map-pin': icons.MapPin,
		stethoscope: icons.Stethoscope,
		brush: icons.Brush,
		scan: icons.Scan,
		podcast: icons.Podcast,
		radio: icons.Radio,
		trophy: icons.Trophy,
		infinity: icons.Infinity,
		sun: icons.Sun,
		moon: icons.Moon,
		'loader-circle': icons.LoaderCircle,
		'log-out': icons.LogOut
	};

	const IconComponent = $derived(iconMap[name]);
</script>

{#if IconComponent}
	<IconComponent {size} {strokeWidth} class={className} />
{/if}
